/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.UserSession;
import java.rmi.RemoteException; // Added for the try-catch block
import java.util.Random;

/**
 *
 * @author User
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private String generatedOtp;
    private javax.swing.JButton loginButton; // Will be the main login button
    private javax.swing.JButton sendOtpButton;
    private javax.swing.JTextField otpField;
    private javax.swing.JLabel otpLabel;


    public LoginForm() {
        initComponents();
        // Initially disable OTP field and final login button
        if (otpField != null) otpField.setEnabled(false);
        if (loginButton != null) loginButton.setEnabled(false); // Assuming loginButton is set in initComponents
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lms_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        // --- OTP Components Declaration ---
        otpLabel = new javax.swing.JLabel();
        otpField = new javax.swing.JTextField();
        sendOtpButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton(); // This should be your existing main login button

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Body.setBackground(new java.awt.Color(255, 255, 255));

        left.setBackground(new java.awt.Color(102, 102, 102));
        left.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(169, 169, 169));
        username.setText("Username");
        username.setToolTipText("Email or Username");
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        lms_icon.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pass.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel3.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("-");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);

        // --- OTP Components Setup ---
        otpLabel.setText("OTP Code:");
        // otpField is already new JTextField()
        sendOtpButton.setText("Send OTP");
        sendOtpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOtpButtonActionPerformed(evt);
            }
        });

        // IMPORTANT: The existing main login button (signInButton or similar from .form file)
        // should be assigned to 'this.loginButton' and its text set.
        // For this example, we assume 'loginButton' is that button.
        // If there's a separate signInButton in the .form, its action needs to be signInActionPerformed.
        // For now, let's assume the primary action button is 'loginButton' (which might be a new one or existing one renamed)
        loginButton.setText("Login"); // Or "Login with OTP"
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt); // Existing signInActionPerformed will handle final login
            }
        });

        // --- Manual GroupLayout modification is NOT done here due to complexity ---
        // --- Developer needs to use NetBeans GUI builder to add: ---
        // --- otpLabel, otpField, sendOtpButton, and ensure loginButton is correctly placed ---
        // --- Example of what GUI builder might generate (simplified): ---
        /*
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    // ... existing components ...
                    .addComponent(sendOtpButton) // Added
                    .addComponent(otpLabel)      // Added
                    .addComponent(otpField)      // Added
                    .addComponent(loginButton)   // Added (or existing button)
                )
                .addGap(74, 74, 74))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createSequentialGroup()
                // ... existing components ...
                .addComponent(sendOtpButton) // Added
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otpLabel)      // Added
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Added
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)   // Added
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        */
        // Using existing layout for now, new components are not visually added by this script.
        // The following is the original layout from the file for other components.
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BodyLayout.createSequentialGroup()
                                .addComponent(passwordTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BodyLayout.createSequentialGroup()
                                .addComponent(lms_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    // Developer: Add sendOtpButton, otpLabel, otpField, loginButton to this GroupLayout using NetBeans GUI Builder
                    // For example (conceptual, not actual code to insert here):
                    // .addComponent(sendOtpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    // .addGroup(BodyLayout.createSequentialGroup().addComponent(otpLabel).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(otpField))
                    // .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112) // Existing Y gap
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lms_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     // passwordTxt might be too short in height if not properly handled in layout
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                // Developer: Add sendOtpButton, otpLabel, otpField, loginButton to this GroupLayout using NetBeans GUI Builder
                // For example (conceptual, not actual code to insert here):
                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED) // Space
                // .addComponent(sendOtpButton)
                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                // .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(otpLabel).addComponent(otpField))
                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                // .addComponent(loginButton)
                .addContainerGap(205, Short.MAX_VALUE)) // Adjust remaining space
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(837, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals("Username")) {
            username.setText("");
        }
        // Removed incorrect passwordTxt.setEchoChar((char) 0) from here.
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")) {
            username.setText("Username");
        }
        // Removed: if (passwordTxt.getText().equals("Password")) { passwordTxt.setEchoChar((char) 0); }
        // This logic is not needed here and was incorrect for lost focus.
        // Placeholder text for password should be handled in passwordFocusLost.
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // Pressing enter in username field might try to submit early.
        // For OTP flow, this should ideally not trigger immediate login.
        // Or, it could trigger the "Send OTP" action if username is filled.
        // For now, let's prevent it from calling signInActionPerformed directly.
        // sendOtpButtonActionPerformed(evt); // Alternative: try to send OTP
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // Use String.valueOf to get text from JPasswordField
        if (String.valueOf(passwordTxt.getPassword()).equals("Password")){
            passwordTxt.setText("");
            passwordTxt.setEchoChar('•');
        }   // TODO add your handling code here:
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (String.valueOf(passwordTxt.getPassword()).equals("") ){
            passwordTxt.setText("Password");
            passwordTxt.setEchoChar((char)0); // Show "Password" placeholder text
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // Pressing enter in password field should not trigger login before OTP.
        // signInActionPerformed(evt); // Remove this direct call
    }//GEN-LAST:event_passwordActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
     //exit
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void sendOtpButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String user = username.getText();
        if (user.isEmpty() || user.equals("Username")) {
            JOptionPane.showMessageDialog(this, "Please enter username to receive OTP.", "OTP Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        generatedOtp = String.format("%06d", new Random().nextInt(999999));
        JOptionPane.showMessageDialog(this, "OTP sent to your registered email (simulated): " + generatedOtp, "OTP Sent", JOptionPane.INFORMATION_MESSAGE);

        if (otpField != null) otpField.setEnabled(true);
        if (loginButton != null) loginButton.setEnabled(true);
        if (sendOtpButton != null) sendOtpButton.setEnabled(false); // Disable after sending
    }

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        String user = username.getText();
        String enteredOtp = (otpField != null) ? otpField.getText() : "";

        if (user.isEmpty() || user.equals("Username")) {
            JOptionPane.showMessageDialog(this, "Username is required.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (generatedOtp == null || generatedOtp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please send OTP first.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (enteredOtp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the OTP.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (enteredOtp.equals(generatedOtp)) {
            try {
                String role;
                if (user.equals("admin")) {
                    role = "admin";
                } else {
                    // Password check can be added here if needed for non-admin users,
                    // or other validation before setting the session.
                    // For now, any non-admin username logs in as "user" with correct OTP.
                    role = "user";
                }

                // Set dummy accountId based on role
                int accountIdToSet = 0; // Default for admin or if other logic fails
                if (role.equals("admin")) {
                    accountIdToSet = 0; // Or -1, or a specific admin user ID if applicable
                } else {
                    accountIdToSet = 1; // Dummy member ID for regular user
                }
                UserSession.getInstance().setUser(user, role, accountIdToSet);

                if (role.equals("admin")) {
                    new AdminDashboard().setVisible(true);
                } else {
                    new UserDashboard().setVisible(true);
                }
                this.dispose();

            } catch (Exception e) { // Catching generic Exception
                JOptionPane.showMessageDialog(this, "Login failed after OTP: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // For debugging
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid OTP. Please try again.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signInActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // Pressing enter in password field should not trigger login before OTP.
        // signInActionPerformed(evt); // Remove this direct call
    }//GEN-LAST:event_passwordTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel left;
    private javax.swing.JLabel lms_icon;
    private javax.swing.JPasswordField passwordTxt;
    // Made username private as it's good practice, static if it needs to be accessed from elsewhere (unlikely for this field)
    private javax.swing.JTextField username;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel left;
    private javax.swing.JLabel lms_icon;
    private javax.swing.JPasswordField passwordTxt;
    // End of variables declaration//GEN-END:variables
    // Manual declaration of new components (otpLabel, otpField, sendOtpButton, loginButton already declared as class members)
}
